trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

strategy:
  matrix:
    Python38:
      python.version: '3.8'

stages:
  - stage: devevlopmentDeployment
    displayName: Deploy dbx notebooks to Dev
    variables:
    - group: qdp-dev-variables


  jobs:
  - deployment: deployNotebooks
    displayName: Deploy Dbx Notebooks
    # environment: 'DEV'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: ../ci/templates/notebook.yml
            parameters:
              azureResourceManagerConnection: 'development_subscription'
              keyVaultName: '$(KEY_VAULT)'
              SubscriptionId: '$(SUBSCRIPTION_ID)'
              RGName: '$(RESOURCE_GROUP)'
              DbxWorkspaceName: '$(DATABRICKS_WORKSPACE_NAME)'
              DbxWorkspaceUrl: '$(DATABRICKS_WORKSPACE_URL)'
              DbxWorkspaceSubDirs: '$(DATABRICKS_WORKSPACE_SUBDIRS)'
              DbxWorkspaceRoot: '$(DATABRICKS_WORKSPACE_ROOT)'